import type { PropsWithChildren } from 'hono/jsx'
import type { BrowserIdentity } from '@hitl-protocol/agent-access'
import type { BrowserSession,Enrollment,Operation,Review } from './store.js'
export function Layout(props:PropsWithChildren<{title:string}>){return <html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>{props.title} · HITL</title><link rel="stylesheet" href="/assets/style.css"/></head><body><header><a href="/">HITL Agent Access</a><nav aria-label="Account"><a href="/account/agents">Connected agents</a></nav></header><main><h1>{props.title}</h1>{props.children}</main><footer>Reference implementation · local demonstration bookings</footer></body></html>}
export function Home(){return <Layout title="Agent Access reference"><p>A verifiable agent identity, a bounded delegation and a human decision are checked separately.</p><p>This demonstration stores catalogue offers and bookings in PostgreSQL. It contacts no external booking or payment provider.</p><a class="button" href="/account/agents">Manage connected agents</a><p><a href="/.well-known/hitl.json">Service discovery</a> · <a href="/openapi.json">OpenAPI</a> · <a href="/v1/catalog">Catalogue</a></p></Layout>}
export function EnrollmentView({enrollment,csrf,expired}:{enrollment:Enrollment;csrf:string;expired:boolean}){return <Layout title="Connect an agent"><p>You are approving this agent connection to your account.</p><dl><dt>Agent supplied name</dt><dd>{enrollment.display_name}</dd><dt>OAuth client</dt><dd>{enrollment.client_id}</dd><dt>Key thumbprint</dt><dd class="identifier">{enrollment.jkt}</dd><dt>Maximum per booking</dt><dd>{money(enrollment.max_total_cents)}</dd><dt>Requested permissions</dt><dd>{enrollment.scopes.join(', ')}</dd><dt>Deadline</dt><dd><time dateTime={enrollment.expires_at}>{enrollment.expires_at}</time></dd></dl>{expired?<p role="status">This connection request has expired.</p>:enrollment.status==='confirmed'?<p role="status">Connection confirmed.</p>:<form method="post"><input type="hidden" name="csrf" value={csrf}/><button type="submit">Connect this agent</button></form>}</Layout>}
export function money(value:number){return new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(value/100)}
export function ReviewView({operation,review,agentName,csrf}:{operation:Operation;review:Review;agentName:string;csrf:string}){
  const expired=Date.now()>=Date.parse(review.expires_at)
  const terminal=expired||['completed','cancelled','expired'].includes(review.status)
  const snapshot=operation.snapshot
  return <Layout title="Review booking proposal"><p>Check the complete proposal before choosing. Your confirmation records a decision; the agent must still execute the booking.</p><dl><dt>Connected agent</dt><dd>{agentName}</dd><dt>Offer</dt><dd>{snapshot.title}</dd><dt>Quantity</dt><dd>{snapshot.quantity}</dd><dt>Unit price</dt><dd>{money(snapshot.unit_price_cents)}</dd><dt>Booking fee</dt><dd>{money(snapshot.fee_cents)}</dd><dt>Total</dt><dd class="total">{money(snapshot.total_cents)}</dd><dt>Refund</dt><dd>{snapshot.refundable?'Refundable':'Non-refundable'}</dd><dt>Terms</dt><dd>{snapshot.terms}</dd><dt>Deadline</dt><dd><time dateTime={review.expires_at}>{review.expires_at}</time></dd></dl><p>No stock is reserved until the agent commits the booking.</p>{terminal?<p role="status">{review.status==='completed'?(review.result?.action==='confirm'?'Confirmation recorded. The booking has not been executed by this decision.':'Proposal declined.'):(expired?'This review has expired.':'This review was cancelled.')}</p>:<form method="post" action={`/review/${encodeURIComponent(review.id)}/respond`}><input type="hidden" name="csrf" value={csrf}/><div class="actions"><button type="submit" name="action" value="confirm">Confirm proposal</button><button class="secondary" type="submit" name="action" value="cancel">Decline proposal</button></div></form>}</Layout>
}
export function AgentsView({agents,csrf,identity}:{agents:{id:string;display_name:string;client_id:string;jkt:string;active:boolean;last_used_at:string|null;grants:{id:string;max_total_cents:number;scopes:string[];active:boolean}[]}[];csrf:string;identity:BrowserIdentity}){return <Layout title="Connected agents"><p>Signed in as {identity.display_name??identity.sub}.</p>{agents.length===0?<p>No agents connected.</p>:agents.map((agent)=><section><h2>{agent.display_name}</h2><p>OAuth client: {agent.client_id}</p><p class="identifier">Key: {agent.jkt}</p><p>Status: {agent.active?'Active':'Revoked'} · Last use: {agent.last_used_at??'Not used'}</p>{agent.grants.filter(grant=>grant.active).map(grant=><div><p>Maximum per booking: {money(grant.max_total_cents)}</p><p>Permissions: {grant.scopes.join(', ')}</p></div>)}{agent.active&&<form method="post" action={`/account/agents/${encodeURIComponent(agent.id)}/revoke`}><input type="hidden" name="csrf" value={csrf}/><button class="secondary" type="submit">Revoke connection</button></form>}</section>)}</Layout>}
export function ErrorView({code,status}:{code:string;status:number}){return <Layout title="Request could not be completed"><p role="alert">{code==='reauthentication_required'?'Please sign in again before making this decision.':code==='expired'?'This request has expired.':code==='state_conflict'?'This request already has a final decision or cannot continue.':code==='version_conflict'?'The proposal has changed. Ask the agent to prepare a new proposal.':status===404?'This page is unavailable for your account.':'Please retry or return to your agent.'}</p><p><a href="/account/agents">Return to your account</a></p></Layout>}
export const STYLE=`:root{color-scheme:light dark;font-family:system-ui,sans-serif;line-height:1.6}*{box-sizing:border-box}body{margin:0;background:#f4f5f8;color:#182536}header,footer{max-width:800px;margin:0 auto;padding:24px}header{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}main{max-width:720px;margin:12px auto 48px;padding:32px;background:white;border-radius:16px;border:1px solid #d7dce3}h1{line-height:1.2;font-size:2rem}a{color:#1759b2;text-underline-offset:3px}dl{display:grid;grid-template-columns:140px 1fr;gap:10px 24px;padding:20px;background:#f4f5f8;border-radius:8px}dt{font-weight:650}dd{margin:0;overflow-wrap:anywhere}.total{font-size:1.4rem;font-weight:700}.identifier{overflow-wrap:anywhere;font-family:monospace}.actions{display:flex;flex-wrap:wrap;gap:12px}button,.button{font:inherit;cursor:pointer;display:inline-block;padding:12px 20px;min-height:48px;border:2px solid #1759b2;border-radius:8px;background:#1759b2;color:white;font-weight:650;text-decoration:none}.secondary{background:white;color:#1759b2}button:focus-visible,a:focus-visible{outline:3px solid #e39100;outline-offset:4px}section{border-top:1px solid #d7dce3;padding:20px 0}footer{font-size:.9rem}@media(max-width:600px){main{margin:8px;padding:20px}dl{grid-template-columns:1fr;gap:4px}dd{margin-bottom:12px}header{padding:16px}}@media(prefers-color-scheme:dark){body{background:#111b28;color:#e9eef5}main,.secondary{background:#182536;color:#e9eef5}dl{background:#111b28}a{color:#83b4ff}}`
